//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partycli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("partycli.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get and save all servers, use command: partycli.exe server_list.
        /// </summary>
        internal static string labelAllServers {
            get {
                return ResourceManager.GetString("labelAllServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string labelChanged {
            get {
                return ResourceManager.GetString("labelChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: There are no server data in local storage.
        /// </summary>
        internal static string labelErrorTherearenoserverdatainlocalstorage {
            get {
                return ResourceManager.GetString("labelErrorTherearenoserverdatainlocalstorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get and save France servers, use command: partycli.exe server_list --france.
        /// </summary>
        internal static string labelFranceServers {
            get {
                return ResourceManager.GetString("labelFranceServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved new server list.
        /// </summary>
        internal static string labelSavedNewServerList {
            get {
                return ResourceManager.GetString("labelSavedNewServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see saved list of servers, use command: partycli.exe server_list --local .
        /// </summary>
        internal static string labelSavedServers {
            get {
                return ResourceManager.GetString("labelSavedServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get and save servers that support TCP protocol, use command: partycli.exe server_list --TCP.
        /// </summary>
        internal static string labelTCPServer {
            get {
                return ResourceManager.GetString("labelTCPServer", resourceCulture);
            }
        }
    }
}
